name: Build DerewolPrint

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd derewolprint
          npm install

      - name: Build Electron app
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd derewolprint
          npm run build
